spring:
  profiles:
    active: local
server:
  port: 8081
---
spring:
  profiles: local
  kafka:
    template:
      topic: test-future-txn-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: future-txn-events-listener-group
